[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 5
force_sort_within_sections = true
known_first_party = ["vasiniyo-hangman"]